services:
  - type: web
    name: FYP-25-S3-15P
    runtime: dotnet-6
    branch: main
    rootDir: FYP-25-S3-15P
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/FYP_25_S3_15P.dll
